from enum import Enum
from typing import Final, TypeAlias


class RouteAccess(Enum):
    PUBLIC = "public"
    AUTHENTICATED = "authenticated"
    AGENT = "agent"


AccessRequirement: TypeAlias = str | RouteAccess

ROUTE_PERMISSION_MATRIX: Final[dict[str, AccessRequirement]] = {
    "POST /api/agent/enroll": RouteAccess.PUBLIC,
    "GET /api/agents": RouteAccess.AUTHENTICATED,
    "GET /api/agents/packages": RouteAccess.AUTHENTICATED,
    "GET /api/agents/packages/{filename}": RouteAccess.PUBLIC,
    "DELETE /api/agents/{agent_id}": "agents:manage",
    "GET /api/agents/{agent_id}": RouteAccess.AUTHENTICATED,
    "PUT /api/agents/{agent_id}": "agents:manage",
    "DELETE /api/agents/{agent_id}/isolate": "agents:manage",
    "POST /api/agents/{agent_id}/isolate": "agents:manage",
    "GET /api/agents/{agent_id}/log-sources": RouteAccess.AUTHENTICATED,
    "POST /api/agents/{agent_id}/log-sources": "agents:manage",
    "DELETE /api/agents/{agent_id}/log-sources/{source_id}": "agents:manage",
    "PUT /api/agents/{agent_id}/log-sources/{source_id}": "agents:manage",
    "GET /api/alerts": "alerts:read",
    "GET /api/alerts/{alert_id}": "alerts:read",
    "PUT /api/alerts/{alert_id}": "alerts:update",
    "GET /api/alerts/{alert_id}/feedback": "alerts:read",
    "POST /api/alerts/{alert_id}/feedback": "alerts:update",
    "POST /api/alerts/{alert_id}/notes": "alerts:update",
    "GET /api/alerts/{alert_id}/source-log": "alerts:read",
    "GET /api/api-keys": "api_keys:manage",
    "POST /api/api-keys": "api_keys:manage",
    "DELETE /api/api-keys/{key_id}": "api_keys:manage",
    "GET /api/artifacts": RouteAccess.AUTHENTICATED,
    "POST /api/artifacts": RouteAccess.AUTHENTICATED,
    "GET /api/artifacts/builtins": RouteAccess.AUTHENTICATED,
    "DELETE /api/artifacts/{artifact_id}": RouteAccess.AUTHENTICATED,
    "PUT /api/artifacts/{artifact_id}": RouteAccess.AUTHENTICATED,
    "POST /api/artifacts/{artifact_id}/run": RouteAccess.AUTHENTICATED,
    "POST /api/assistant/chat": "alerts:read",
    "GET /api/audit-logs": RouteAccess.AUTHENTICATED,
    "GET /api/audit-logs/verify": "audit:verify",
    "POST /api/auth/login": RouteAccess.PUBLIC,
    "GET /api/auth/me": RouteAccess.AUTHENTICATED,
    "POST /api/auth/mfa/disable": RouteAccess.AUTHENTICATED,
    "POST /api/auth/mfa/enable": RouteAccess.AUTHENTICATED,
    "POST /api/auth/mfa/setup": RouteAccess.AUTHENTICATED,
    "POST /api/auth/refresh": RouteAccess.PUBLIC,
    "GET /api/bookmarks": RouteAccess.AUTHENTICATED,
    "POST /api/bookmarks": RouteAccess.AUTHENTICATED,
    "DELETE /api/bookmarks/{bookmark_id}": RouteAccess.AUTHENTICATED,
    "GET /api/cases": RouteAccess.AUTHENTICATED,
    "POST /api/cases": "cases:manage",
    "DELETE /api/cases/{case_id}": "cases:manage",
    "GET /api/cases/{case_id}": RouteAccess.AUTHENTICATED,
    "PUT /api/cases/{case_id}": "cases:manage",
    "POST /api/cases/{case_id}/escalate": "cases:manage",
    "GET /api/cases/{case_id}/feedback": RouteAccess.AUTHENTICATED,
    "POST /api/cases/{case_id}/feedback": RouteAccess.AUTHENTICATED,
    "POST /api/cases/{case_id}/notes": RouteAccess.AUTHENTICATED,
    "GET /api/cases/{case_id}/timeline": RouteAccess.AUTHENTICATED,
    "GET /api/cases/{case_id}/export": RouteAccess.AUTHENTICATED,
    "GET /api/decoders": "logs:read",
    "POST /api/decoders": "decoders:create",
    "POST /api/decoders/test": "decoders:create",
    "DELETE /api/decoders/{decoder_id}": "decoders:delete",
    "PUT /api/decoders/{decoder_id}": "decoders:update",
    "GET /api/enrollment-tokens": RouteAccess.AUTHENTICATED,
    "POST /api/enrollment-tokens": RouteAccess.AUTHENTICATED,
    "DELETE /api/enrollment-tokens/{token_id}": RouteAccess.AUTHENTICATED,
    "GET /api/entities/{entity_type}/{entity_value}": "logs:read",
    "GET /api/events": "logs:read",
    "GET /api/export/alerts": RouteAccess.AUTHENTICATED,
    "GET /api/export/alerts/csv": RouteAccess.AUTHENTICATED,
    "POST /api/exports/verify": RouteAccess.AUTHENTICATED,
    "POST /api/fim": RouteAccess.AGENT,
    "GET /api/fim/events": RouteAccess.AUTHENTICATED,
    "GET /api/fim/paths": RouteAccess.AUTHENTICATED,
    "POST /api/fim/paths": RouteAccess.AUTHENTICATED,
    "DELETE /api/fim/paths/{path_id}": RouteAccess.AUTHENTICATED,
    "PATCH /api/fim/paths/{path_id}": RouteAccess.AUTHENTICATED,
    "GET /api/fleet-hunts": RouteAccess.AUTHENTICATED,
    "POST /api/fleet-hunts": RouteAccess.AUTHENTICATED,
    "GET /api/fleet-hunts/{hunt_id}": RouteAccess.AUTHENTICATED,
    "GET /api/fleet-hunts/{hunt_id}/tasks": RouteAccess.AUTHENTICATED,
    "GET /api/handover": RouteAccess.AUTHENTICATED,
    "POST /api/handover": RouteAccess.AUTHENTICATED,
    "GET /api/hunt-schedules": RouteAccess.AUTHENTICATED,
    "POST /api/hunt-schedules": RouteAccess.AUTHENTICATED,
    "DELETE /api/hunt-schedules/{schedule_id}": RouteAccess.AUTHENTICATED,
    "PATCH /api/hunt-schedules/{schedule_id}/toggle": RouteAccess.AUTHENTICATED,
    "GET /api/hunts": RouteAccess.AUTHENTICATED,
    "POST /api/hunts": RouteAccess.AUTHENTICATED,
    "GET /api/hunts/{hunt_id}": RouteAccess.AUTHENTICATED,
    "POST /api/hygiene": RouteAccess.AGENT,
    "GET /api/hygiene/latest": RouteAccess.AUTHENTICATED,
    "GET /api/hygiene/{agent_id}": RouteAccess.AUTHENTICATED,
    "GET /api/hygiene/{agent_id}/vulns": RouteAccess.AUTHENTICATED,
    "POST /api/ingest/heartbeat": RouteAccess.AGENT,
    "POST /api/ingest/log": RouteAccess.AGENT,
    "GET /api/iocs/{indicator}": "iocs:read",
    "GET /api/logs": "logs:read",
    "GET /api/metrics/soc": RouteAccess.AUTHENTICATED,
    "GET /api/metrics/ti/quick": RouteAccess.AUTHENTICATED,
    "GET /api/metrics/worker": RouteAccess.AUTHENTICATED,
    "GET /api/metrics/workload": RouteAccess.AUTHENTICATED,
    "GET /api/mitre/heatmap": RouteAccess.AUTHENTICATED,
    "GET /api/command-center/situation-brief": RouteAccess.AUTHENTICATED,
    "GET /api/queues/metrics": "queues:manage",
    "GET /api/queues/webhook-deliveries": "queues:manage",
    "POST /api/queues/webhook-deliveries/{delivery_id}/retry": "queues:manage",
    "POST /api/queues/webhook-deliveries/{delivery_id}/discard": "queues:manage",
    "POST /api/reports/generate": "alerts:read",
    "GET /api/rules": "logs:read",
    "POST /api/rules": "rules:create",
    "POST /api/rules/hunt": "logs:read",
    "POST /api/rules/import": "rules:create",
    "POST /api/rules/import/repository": "rules:create",
    "POST /api/rules/test": "rules:create",
    "DELETE /api/rules/{rule_id}": "rules:delete",
    "PUT /api/rules/{rule_id}": "rules:update",
    "POST /api/rules/{rule_id}/approve": "rules:update",
    "GET /api/rules/{rule_id}/diff": "logs:read",
    "GET /api/rules/{rule_id}/export": "logs:read",
    "GET /api/rules/{rule_id}/quality": "logs:read",
    "GET /api/rules/{rule_id}/revisions": "logs:read",
    "POST /api/rules/{rule_id}/rollback/{version}": "rules:update",
    "GET /api/retention-policies": "settings:manage",
    "PUT /api/retention-policies": "settings:manage",
    "GET /api/retention-policies/usage": "settings:manage",
    "GET /api/saved-queries": RouteAccess.AUTHENTICATED,
    "POST /api/saved-queries": RouteAccess.AUTHENTICATED,
    "DELETE /api/saved-queries/{query_id}": RouteAccess.AUTHENTICATED,
    "GET /api/search": RouteAccess.AUTHENTICATED,
    "GET /api/settings": "settings:manage",
    "GET /api/sla-policies": "settings:manage",
    "PUT /api/sla-policies/{severity}": "settings:manage",
    "PUT /api/settings/{key}": "settings:manage",
    "DELETE /api/soar/actions/{action_id}": RouteAccess.AUTHENTICATED,
    "PATCH /api/soar/actions/{action_id}": RouteAccess.AUTHENTICATED,
    "GET /api/soar/executions": RouteAccess.AUTHENTICATED,
    "POST /api/soar/executions/{execution_id}/approve": RouteAccess.AUTHENTICATED,
    "POST /api/soar/executions/{execution_id}/rollback": RouteAccess.AUTHENTICATED,
    "GET /api/soar/playbooks": RouteAccess.AUTHENTICATED,
    "POST /api/soar/playbooks": RouteAccess.AUTHENTICATED,
    "DELETE /api/soar/playbooks/{playbook_id}": RouteAccess.AUTHENTICATED,
    "GET /api/soar/playbooks/{playbook_id}": RouteAccess.AUTHENTICATED,
    "PATCH /api/soar/playbooks/{playbook_id}": RouteAccess.AUTHENTICATED,
    "POST /api/soar/playbooks/{playbook_id}/actions": RouteAccess.AUTHENTICATED,
    "GET /api/sop-documents": RouteAccess.AUTHENTICATED,
    "POST /api/sop-documents": RouteAccess.AUTHENTICATED,
    "DELETE /api/sop-documents/{doc_id}": RouteAccess.AUTHENTICATED,
    "GET /api/suppressions": RouteAccess.AUTHENTICATED,
    "POST /api/suppressions": "alerts:manage",
    "DELETE /api/suppressions/{suppression_id}": "alerts:manage",
    "GET /api/tasks": RouteAccess.AUTHENTICATED,
    "POST /api/tasks": RouteAccess.AUTHENTICATED,
    "DELETE /api/tasks/{task_id}": RouteAccess.AUTHENTICATED,
    "GET /api/tasks/{task_id}": RouteAccess.AUTHENTICATED,
    "POST /api/tasks/{task_id}/result": RouteAccess.AGENT,
    "GET /api/ueba/entities": "alerts:read",
    "GET /api/ueba/entity/{entity_type}/{entity_value}": "alerts:read",
    "GET /api/ueba/status": "alerts:read",
    "GET /api/ueba/{entity_type}/{entity_value}/history": "alerts:read",
    "GET /api/users": "users:manage",
    "POST /api/users": "users:manage",
    "DELETE /api/users/{user_id}": "users:manage",
    "PUT /api/users/{user_id}": "users:manage",
    "GET /api/webhooks": "agents:manage",
    "POST /api/webhooks": "agents:manage",
    "DELETE /api/webhooks/{webhook_id}": "agents:manage",
    "PUT /api/webhooks/{webhook_id}": "agents:manage",
    "GET /api/yara-rules": RouteAccess.AUTHENTICATED,
    "POST /api/yara-rules": RouteAccess.AUTHENTICATED,
    "GET /api/yara-rules/builtins": RouteAccess.AUTHENTICATED,
    "POST /api/yara-rules/scan": RouteAccess.AUTHENTICATED,
    "POST /api/yara-rules/seed-builtins": RouteAccess.AUTHENTICATED,
    "DELETE /api/yara-rules/{rule_id}": RouteAccess.AUTHENTICATED,
    "PUT /api/yara-rules/{rule_id}": RouteAccess.AUTHENTICATED,
    "PATCH /api/yara-rules/{rule_id}/toggle": RouteAccess.AUTHENTICATED,
    "GET /health": RouteAccess.PUBLIC,
    "GET /metrics": RouteAccess.PUBLIC,
}

PUBLIC_OPERATIONS: Final[frozenset[str]] = frozenset(
    {
        "POST /api/agent/enroll",
        "GET /api/agents/packages/{filename}",
        "POST /api/auth/login",
        "POST /api/auth/refresh",
        "GET /health",
        "GET /metrics",
    }
)
